name: MinecraftEvacuation
version: '${project.version}'
main: com.bananaarch.minecraftevacuation.MinecraftEvacuation
api-version: 1.19
commands:
  menu:
    description: Opens the menu GUI for the MinecraftEvacuation plugin.
    aliases: [menu, setting, settings, manager]